#creates the executable from both the object files
lab13test: lab_13_unit_test.o 
	g++ -Wall -g -o lab13test lab_13_unit_test.o
	

#creates the unit test object file
lab_13_unit_test: lab_13_unit_test.cpp
	g++ -Wall -g -c lab_13_unit_test.cpp