lab20test: lab_20.o lab_20_unit_test.o
	g++ -Wall -g -o lab20 lab_20.o lab_20_unit_test.o

lab20: lab_20.cpp
	g++ -Wall -g -c lab_20.cpp
	
lab20unittest: lab_20_unit_test.cpp
	g++ -Wall -g -c lab_20_unit_test.cpp